site_name: Flask Express
site_description: provide the interactive service like expressJs to the flask app.
site_url: https://marktennyson.github.io/flask-express
dev_addr: 127.0.0.1:8080

theme:
  name: material
  palette:
  - scheme: default
    primary: teal
    accent: amber
    toggle:
      icon: material/lightbulb-outline
      name: Switch to light mode
  - scheme: slate
    primary: teal
    accent: amber
    toggle:
      icon: material/lightbulb
      name: Switch to dark mode
  logo: https://raw.githubusercontent.com/marktennyson/flask-express/main/logos/flask-express-logo.png
  favicon: https://raw.githubusercontent.com/marktennyson/flask-express/main/logos/flask-express-logo.png
  features:
  - search.suggest
  - search.highlight
  - content.tabs.link
  icon:
    repo: fontawesome/brands/github-alt

repo_name: marktennyson/Flask-Express
repo_url: https://github.com/marktennyson/flask-express

plugins:
- search
- markdownextradata:
    data: data

markdown_extensions:
  - attr_list
  - toc:
      permalink: true
  
  - pymdownx.highlight:
      linenums: false
    
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg

  - pymdownx.superfences

nav:
  - Flask-Express: index.md
  - Request Class: request.md
  - Response Class: response.md
  - Munch Class: munch.md
  - Tutorial: tutorial.md
  - Examples: examples.md