"""empty message

Revision ID: 4abd1e0ec5d6
Revises: 
Create Date: 2021-09-20 09:46:20.717737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4abd1e0ec5d6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_change_password_otp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contactnumber', sa.String(length=100), nullable=True),
    sa.Column('otp', sa.String(length=100), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('agent_change_password_otp')
    # ### end Alembic commands ###
